# Generated by Django 6.0.4 on 2026-04-27 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='phrasalverb.grammarpattern')),
            ],
        ),
        migrations.AddField(
            model_name='grammarpattern',
            name='particle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='phrasalverb.particle'),
        ),
        migrations.AddField(
            model_name='particle',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particles', to='phrasalverb.verb'),
        ),
    ]
