# Generated by Django 6.0.4 on 2026-04-27 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasalverb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaning',
            old_name='pattern',
            new_name='grammar',
        ),
        migrations.RenameField(
            model_name='particle',
            old_name='particle',
            new_name='preposition',
        ),
        migrations.RemoveField(
            model_name='grammarpattern',
            name='grammar',
        ),
        migrations.AddField(
            model_name='grammarpattern',
            name='pattern',
            field=models.CharField(default='temp', help_text='vd: take up + noun', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammarpattern',
            name='particle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammars', to='phrasalverb.particle'),
        ),
        migrations.AlterUniqueTogether(
            name='particle',
            unique_together={('verb', 'preposition')},
        ),
    ]
