# Generated by Django 6.0.4 on 2026-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasalverb', '0002_rename_pattern_meaning_grammar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammarpattern',
            options={'ordering': ['pattern']},
        ),
        migrations.AlterModelOptions(
            name='particle',
            options={'ordering': ['preposition']},
        ),
        migrations.AlterModelOptions(
            name='verb',
            options={'ordering': ['word']},
        ),
        migrations.AlterUniqueTogether(
            name='particle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='particle',
            name='preposition',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='verb',
            name='word',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='grammarpattern',
            constraint=models.UniqueConstraint(fields=('particle', 'pattern'), name='unique_particle_pattern'),
        ),
        migrations.AddConstraint(
            model_name='particle',
            constraint=models.UniqueConstraint(fields=('verb', 'preposition'), name='unique_verb_preposition'),
        ),
    ]
